// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "github.com/jordyf15/tweeter-api/models"
	mock "github.com/stretchr/testify/mock"

	user "github.com/jordyf15/tweeter-api/user"

	utils "github.com/jordyf15/tweeter-api/utils"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// ChangeUserPassword provides a mock function with given fields: userID, oldPassword, newPassword
func (_m *Usecase) ChangeUserPassword(userID string, oldPassword string, newPassword string) error {
	ret := _m.Called(userID, oldPassword, newPassword)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(userID, oldPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: _a0
func (_m *Usecase) Create(_a0 *models.User) (map[string]interface{}, error) {
	ret := _m.Called(_a0)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(*models.User) map[string]interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.User) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EditUserProfile provides a mock function with given fields: userID, updates, profileImageReader, backgroundImageReader, willRemoveProfileImage, willRemoveBackgroundImage
func (_m *Usecase) EditUserProfile(userID string, updates map[string]string, profileImageReader utils.NamedFileReader, backgroundImageReader utils.NamedFileReader, willRemoveProfileImage bool, willRemoveBackgroundImage bool) (*models.User, error) {
	ret := _m.Called(userID, updates, profileImageReader, backgroundImageReader, willRemoveProfileImage, willRemoveBackgroundImage)

	var r0 *models.User
	if rf, ok := ret.Get(0).(func(string, map[string]string, utils.NamedFileReader, utils.NamedFileReader, bool, bool) *models.User); ok {
		r0 = rf(userID, updates, profileImageReader, backgroundImageReader, willRemoveProfileImage, willRemoveBackgroundImage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, map[string]string, utils.NamedFileReader, utils.NamedFileReader, bool, bool) error); ok {
		r1 = rf(userID, updates, profileImageReader, backgroundImageReader, willRemoveProfileImage, willRemoveBackgroundImage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// For provides a mock function with given fields: _a0
func (_m *Usecase) For(_a0 *models.User) user.InstanceUsecase {
	ret := _m.Called(_a0)

	var r0 user.InstanceUsecase
	if rf, ok := ret.Get(0).(func(*models.User) user.InstanceUsecase); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user.InstanceUsecase)
		}
	}

	return r0
}

// Login provides a mock function with given fields: login, password
func (_m *Usecase) Login(login string, password string) (map[string]interface{}, error) {
	ret := _m.Called(login, password)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string, string) map[string]interface{}); ok {
		r0 = rf(login, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(login, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
