// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	models "github.com/jordyf15/tweeter-api/models"
	mock "github.com/stretchr/testify/mock"

	utils "github.com/jordyf15/tweeter-api/utils"
)

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// Create provides a mock function with given fields: _a0, groupImage
func (_m *Usecase) Create(_a0 *models.Group, groupImage utils.NamedFileReader) (*models.Group, error) {
	ret := _m.Called(_a0, groupImage)

	var r0 *models.Group
	if rf, ok := ret.Get(0).(func(*models.Group, utils.NamedFileReader) *models.Group); ok {
		r0 = rf(_a0, groupImage)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Group)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*models.Group, utils.NamedFileReader) error); ok {
		r1 = rf(_a0, groupImage)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewUsecase interface {
	mock.TestingT
	Cleanup(func())
}

// NewUsecase creates a new instance of Usecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUsecase(t mockConstructorTestingTNewUsecase) *Usecase {
	mock := &Usecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
